<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Akshays-MacBook-Air.local" failures="1" tests="1" name="firefoxtest" time="54.619" errors="0" timestamp="2025-01-31T19:56:03 IST">
  <testcase classname="testCases.TC01_AccountRegistrationTest" name="Verifry_Account_Registration" time="22.058">
    <failure type="java.lang.AssertionError" message="Test case failed due to an exception.">
      <![CDATA[java.lang.AssertionError: Test case failed due to an exception.
at testCases.TC01_AccountRegistrationTest.Verifry_Account_Registration(TC01_AccountRegistrationTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Verifry_Account_Registration -->
</testsuite> <!-- firefoxtest -->
